# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
