# Generated by Django 4.1.13 on 2024-02-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.TextField()),
            ],
            options={
                "verbose_name_plural": "activities",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("institution", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvailableYears",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.TextField()),
            ],
            options={
                "verbose_name_plural": "frequencies",
            },
        ),
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funding", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="JournalOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journal_name", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Journal options",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.TextField()),
                ("activities", models.ManyToManyField(to="publisher.activity")),
                ("experiments", models.ManyToManyField(to="publisher.experiment")),
                ("frequencies", models.ManyToManyField(to="publisher.frequency")),
                ("keywords", models.ManyToManyField(to="publisher.keyword")),
                ("models", models.ManyToManyField(to="publisher.model")),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_type",
                    models.IntegerField(
                        choices=[
                            (0, "Book"),
                            (1, "Conference"),
                            (2, "Journal"),
                            (3, "Magazine"),
                            (4, "Poster"),
                            (5, "Presentation"),
                            (6, "Technical Report"),
                            (7, "Other"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Published"),
                            (1, "Submitted"),
                            (2, "Accepted"),
                            (3, "Not Applicable"),
                        ],
                        default=0,
                    ),
                ),
                ("title", models.TextField()),
                ("project_number", models.TextField()),
                ("task_number", models.TextField()),
                ("publication_date", models.DateField()),
                ("url", models.URLField()),
                ("doi", models.TextField(blank=True)),
                ("abstract", models.TextField()),
                ("activities", models.ManyToManyField(to="publisher.activity")),
                ("authors", models.ManyToManyField(to="publisher.author")),
                ("experiments", models.ManyToManyField(to="publisher.experiment")),
                ("frequency", models.ManyToManyField(to="publisher.frequency")),
                ("funding", models.ManyToManyField(to="publisher.funding")),
                ("keywords", models.ManyToManyField(to="publisher.keyword")),
            ],
        ),
        migrations.CreateModel(
            name="Realm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("realm", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.TextField()),
                ("editor", models.TextField(blank=True)),
                ("issuer", models.TextField(blank=True)),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PubModels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ensemble", models.IntegerField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.model",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publication",
            name="model",
            field=models.ManyToManyField(
                through="publisher.PubModels", to="publisher.model"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="projects",
            field=models.ManyToManyField(to="publisher.project"),
        ),
        migrations.AddField(
            model_name="publication",
            name="realms",
            field=models.ManyToManyField(to="publisher.realm"),
        ),
        migrations.AddField(
            model_name="publication",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="variables",
            field=models.ManyToManyField(to="publisher.variable"),
        ),
        migrations.AddField(
            model_name="project",
            name="realms",
            field=models.ManyToManyField(to="publisher.realm"),
        ),
        migrations.AddField(
            model_name="project",
            name="variables",
            field=models.ManyToManyField(to="publisher.variable"),
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presentation_title", models.TextField()),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster_title", models.TextField()),
                ("event", models.TextField(blank=True)),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingDoi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_pub", models.TextField()),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("magazine_name", models.TextField()),
                ("editor", models.TextField(blank=True)),
                ("volume_number", models.TextField(blank=True)),
                ("article_number", models.TextField(blank=True)),
                ("start_page", models.TextField(blank=True)),
                ("end_page", models.TextField(blank=True)),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.TextField(blank=True)),
                ("article_number", models.TextField(blank=True)),
                ("start_page", models.TextField(blank=True)),
                ("end_page", models.TextField(blank=True)),
                (
                    "journal_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.journaloptions",
                    ),
                ),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conference_name", models.TextField()),
                ("conference_serial_number", models.TextField(blank=True)),
                ("event_location", models.TextField(blank=True)),
                ("start_page", models.TextField(blank=True)),
                ("end_page", models.TextField(blank=True)),
                ("editor", models.TextField(blank=True)),
                ("city_of_publication", models.TextField(blank=True)),
                ("publisher", models.TextField(blank=True)),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.TextField()),
                ("chapter_title", models.TextField(blank=True)),
                ("start_page", models.TextField(blank=True)),
                ("end_page", models.TextField(blank=True)),
                ("editor", models.TextField(blank=True)),
                ("city_of_publication", models.TextField(blank=True)),
                ("publisher", models.TextField(blank=True)),
                (
                    "publication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publication",
                    ),
                ),
            ],
        ),
    ]
