version: "3"

volumes:
  production_traefik: {}

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        host_name: ${DOMAIN_NAME}
        backend_prefix: ${DOMAIN_SUBDIRECTORY}
    image: pubhub_production_traefik
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
