journal_names = [
    'Acta Meteorologica Sinica',
    'Advances in Atmospheric Sciences',
    'Advances in Geosciences',
    'Advances in Meteorology',
    'Advances in Space Research',
    'Aerosol Science and Technology',
    'American Scientist',
    'Applied Mathematics and Computation',
    'Applied Optics',
    'Atmosphere',
    'Atmospheric and Oceanic Optics',
    'Atmospheric Chemistry and Physics',
    'Atmospheric Environment',
    'Atmospheric Research',
    'Atmospheric Science Letters',
    'Australian Meteorological and Oceanographic Journal',
    'Biogeosciences',
    'Biogeosciences Discussions',
    'Boundary-Layer Meteorology',
    'Bulletin of the American Meteorological Society',
    'Chines Science bulletin',
    'Climate Dynamics',
    'Climate of the Past',
    'Climate of the Past Discussions',
    'Climate Research',
    'Climatic Change',
    'Contributions to Atmospheric Physics',
    'Current Science',
    'Deep Sea Research',
    'Dynamics of Atmospheres and Oceans',
    'Earth and Planetary Science Letters',
    'Earth Interactions',
    'Earth System Dynamics',
    'ECMWF Newsletter',
    'Environmental Research Letters',
    'Environmental Science & Technology',
    'Eos',
    'EOS, Transactions',
    'Fractals',
    'Geophysical Research Letters',
    'Geoscience and Remote Sensing Letters',
    'Geoscientific Model Development',
    'Geoscientific Model Development Discussions',
    'Global Biogeochemical Cycles',
    'Global Change Biology',
    'Hydrology and Earth System Sciences',
    'Hydrology and Earth System Sciences Discussions',
    'IEEE Transactions on Geoscience and Remote Sensing',
    'International Journal of Climatology',
    'Izvestiya, Atmospheric and Oceanic Physics',
    'Journal of Advances in Modeling Earth Systems',
    'Journal of Aerosol Science',
    'Journal of Agriculture and Forest Meteorology',
    'Journal of Applied Meteorology',
    'Journal of Applied Meteorology and Climatology',
    'Journal of Applied Physics',
    'Journal of Atmopspheric Sciences',
    'Journal of Atmospheric and Oceanic Technology',
    'Journal of Biogeography',
    'Journal of Climate',
    'Journal of Geophysical Research',
    'Journal of Geophysical Research-Atmospheres',
    'Journal of Hydrometeorology',
    'Journal of Molecular Structure',
    'Journal of Quantitative Spectroscopy & Radiative Transfer',
    'Journal of the Atmospheric Sciences',
    'Journal of the Meteorological Society of Japan',
    'Local Environment',
    'Meteorology and Atmospheric Physics',
    'Molecular Ecology',
    'Monthly Weather Review',
    'Nature',
    'Nature Climate Change',
    'Nature Geoscience',
    'Nonlinear Processes in Geophysics',
    'Nuclear Science Engineering',
    'Ocean Modelling',
    'Palaeogeography, Palaeoclimatology, Palaeoecology',
    'Physical Review Letters',
    'Physics and Chemistry of the Earth',
    'Physics Today',
    'Proceedings of the National Academy of Sciences',
    'Quarterly Journal Royal Meteorological Society',
    'Quaternary Science Reviews',
    'Radio Science',
    'Remote Sensing',
    'Remote Sensing Environment',
    'Reviews of Geophysics',
    'Science',
    'Scientific American',
    'SOLA',
    'Tellus',
    'Terrestrial, Atmospheric and Oceanic Sciences',
    'The Cryosphere',
    'The Cryosphere Discussions',
    'The Holocene',
    'Theoretical and Applied Climatology',
    'Water Resources Research',
    'Weather and Forecasting',
    'Other'
]