journal_names = [
    "AGU Advances",
    "Acta Meteorologica Sinica",
    "Advances in Atmospheric Sciences",
    "Advances in Geosciences",
    "Advances in Meteorology",
    "Advances in Space Research",
    "Advances in Statistical Climatology, Meteorology and Oceanography",
    "Aerosol Science and Technology",
    "American Scientist",
    "Applied Mathematics and Computation",
    "Applied Optics",
    "Atmosphere",
    "Atmospheric Chemistry and Physics",
    "Atmospheric Environment",
    "Atmospheric Research",
    "Atmospheric Science Letters",
    "Atmospheric and Oceanic Optics",
    "Australian Meteorological and Oceanographic Journal",
    "Biogeosciences",
    "Biogeosciences Discussions",
    "Biological Conservation",
    "Boundary-Layer Meteorology",
    "Bulletin of the American Meteorological Society",
    "CATENA",
    "Chines Science bulletin",
    "Climate Dynamics",
    "Climate Research",
    "Climate of the Past",
    "Climate of the Past Discussions",
    "Climatic Change",
    "Conservation Science and Practice",
    "Contributions to Atmospheric Physics",
    "Current Science",
    "Data in Brief",
    "Deep Sea Research",
    "Dynamics of Atmospheres and Oceans",
    "ECMWF Newsletter",
    "EOS, Transactions",
    "Earth Interactions",
    "Earth System Dynamics",
    "Earth and Planetary Science Letters",
    "Earth and Space Science",
    "Earth's Future",
    "Environmental Research Letters",
    "Environmental Science & Technology",
    "Eos",
    "Forensic Science International: Reports",
    "Fractals",
    "Frontiers in Earth Science",
    "Geophysical Research Letters",
    "Geoscience Data Journal",
    "Geoscience and Remote Sensing Letters",
    "Geoscientific Model Development",
    "Geoscientific Model Development Discussions",
    "Global Biogeochemical Cycles",
    "Global Change Biology",
    "Global and Planetary Change",
    "Hydrology and Earth System Sciences",
    "Hydrology and Earth System Sciences Discussions",
    "ICES Journal of Marine Science",
    "IEEE Transactions on Geoscience and Remote Sensing",
    "International Journal of Climatology",
    "Izvestiya, Atmospheric and Oceanic Physics",
    "Journal of Advances in Modeling Earth Systems",
    "Journal of Aerosol Science",
    "Journal of Agriculture and Forest Meteorology",
    "Journal of Applied Meteorology",
    "Journal of Applied Meteorology and Climatology",
    "Journal of Applied Physics",
    "Journal of Atmopspheric Sciences",
    "Journal of Atmospheric and Oceanic Technology",
    "Journal of Biogeography",
    "Journal of Climate",
    "Journal of Geophysical Research",
    "Journal of Geophysical Research-Atmospheres",
    "Journal of Geophysical Research: Oceans",
    "Journal of Hydrometeorology",
    "Journal of Molecular Structure",
    "Journal of Oceanography",
    "Journal of Quantitative Spectroscopy & Radiative Transfer",
    "Journal of Southern Hemisphere Earth Systems Science",
    "Journal of the Atmospheric Sciences",
    "Journal of the Meteorological Society of Japan",
    "Local Environment",
    "Meteorology and Atmospheric Physics",
    "Molecular Ecology",
    "Monthly Weather Review",
    "Nature",
    "Nature Climate Change",
    "Nature Communications",
    "Nature Geoscience",
    "Nature Reviews Earth &amp; Environment",
    "Nonlinear Processes in Geophysics",
    "Nuclear Science Engineering",
    "Ocean Modelling",
    "Ocean Science Journal",
    "Other",
    "Palaeogeography, Palaeoclimatology, Palaeoecology",
    "Past Global Changes Magazine",
    "Physical Review Letters",
    "Physics Today",
    "Physics and Chemistry of the Earth",
    "Proceedings of the National Academy of Sciences",
    "Progress in Earth and Planetary Science",
    "Quarterly Journal Royal Meteorological Society",
    "Quaternary Science Reviews",
    "Radio Science",
    "Remote Sensing",
    "Remote Sensing Environment",
    "Reviews of Geophysics",
    "Royal Society Open Science",
    "SOLA",
    "Science",
    "Science Advances",
    "Science China Earth Sciences",
    "Scientific American",
    "Scientific Data",
    "Scientific Reports",
    "Sustainability",
    "Tellus",
    "Terrestrial, Atmospheric and Oceanic Sciences",
    "The Cryosphere",
    "The Cryosphere Discussions",
    "The Holocene",
    "Theoretical and Applied Climatology",
    "Water",
    "Water Resources Research",
    "Weather and Climate Extremes",
    "Weather and Forecasting",
    "npj Climate and Atmospheric Science"
]
