keyword_data = [
    {'project_name': 'CMIP5',
     'keywords': [
         'Abrupt change',
         'Acidification',
         'Adaptation',
         'Aerosols',
         'Agriculture',
         'AMO',
         'Annual cycle',
         'Antarctica',
         'Arctic Ocean',
         'Asia',
         'Aspects studied',
         'Atlantic Ocean',
         'Atmospheric chemistry',
         'Australia and New Zealand',
         'Biogeochemical cycles',
         'Blocking',
         'Carbon cycle',
         'Central America',
         'Central and North Asia',
         'Climate sensitivity',
         'Climatology',
         'Clouds',
         'Coastal regions',
         'Decadal prediction',
         'Decade-century variability',
         'Deserts',
         'Detection & attribution',
         'Diurnal cycle',
         'Downscaling',
         'Eastern Asia',
         'Ecosystem',
         'Energy budget',
         'Energy supply/use',
         'ENSO',
         'Europe',
         'Extratropical storms',
         'Extremes',
         'Feedbacks',
         'Forestry',
         'Globe',
         'Health',
         'high latitudes',
         'Hydrological cycle',
         'Ice sheets /glaciers',
         'idealized Aqua-planet',
         'Indian Ocean',
         'Industry',
         'Interannual variability',
         'Irreversibility',
         'Jets',
         'Land surface',
         'Land use',
         'Mediterranean Sea',
         'mid-latitudes',
         'Middle East and Southern',
         'Mitigation',
         'Modes of variability',
         'Monsoons',
         'Mountains',
         'NAM',
         'NAO',
         'None',
         'North America',
         'NPO',
         'Ocean heat content',
         'Other Islands',
         'Pacific Islands',
         'Pacific Ocean',
         'Paleoclimate',
         'PDO',
         'Permafrost',
         'PNA',
         'Prairies',
         'Predictability',
         'Primary IPCC audience',
         'Projection',
         'PSA',
         'Radiatiave forcing',
         'Radiation',
         'Rain forests',
         'Rare events',
         'Region studied',
         'Satellite simulator',
         'Scientific focus',
         'Sea ice',
         'Sea level',
         'South America',
         'Southeast Asia',
         'Southern Ocean',
         'Storm tracks',
         'Surface fluxes',
         'Sustainability',
         'TBO',
         'Tropical storms',
         'Tropics',
         'Tundra',
         'Uncertainty',
         'Unforced variability',
         'Vegetation',
         'Volcanoes',
         'Vulnerability',
         'Water resources',
         'Weather',
         'WG1 (physical climate system)',
         'WG2 (climate change impacts)',
         'WG3 (assessment / mitigation)',
         'Other'
     ]},
    {'project_name': 'CMIP6',
     'keywords': [

     ]},

]
