replaced_frequencies = {
    'CMIP5': {},
    'CMIP6': {
        '1hr': '1-hourly',
        '1hrCM': '1-hourly',
        '1hrPt': '1-hourly',
        '3hr': '3-hourly',
        '3hrPt': '3-hourly',
        '6hr': '6-hourly',
        '6hrPt': '6-hourly',
        'day': 'Daily',
        'dec': 'Decadal',
        'fx': 'Fixed',
        'mon': 'Monthly',
        'monC': 'Climatology Monthly Mean',
        'monPt': 'Monthly',
        'subhrPt': 'Sub-Hourly',
        'yr': 'Yearly',
        'yrPt': 'Yearly'
    }
}

removed_frequencies = [
    '1hr',
    '1hrCM',
    '1hrPt',
    '3hr',
    '3hrPt',
    '6hr',
    '6hrPt',
    'day',
    'dec',
    'fx',
    'mon',
    'monC',
    'monPt',
    'subhrPt',
    'yr',
    'yrPt'
]

replaced_experiments = {
    'CMIP5': {
        'esmFdbk2': '1pctCO2-rad',
        'abrupt4xCO2': 'abrupt-4xCO2',
        'amip4xCO2': 'amip-4xCO2',
        'amipFuture': 'amip-future4K',
        'amip4K': 'amip-p4K',
        'aqua4xCO2': 'aqua-4xCO2',
        'aquaControl': 'aqua-control',
        'aqua4K': 'aqua-p4K',
        'esmHistorical': 'esm-hist',
        'esmControl': 'esm-piControl',
        'historicalGHG': 'hist-GHG',
        'historicalNat': 'hist-nat',
        'historicalExt': 'historical-ext',
        'rcp26': 'rcp26-cmip5',
        'rcp45': 'rcp45-cmip5',
        'rcp60': 'rcp60-cmip5',
        'rcp85': 'rcp85-cmip5'
    },
    'CMIP6': {}
}

removed_experiments = [
    'esmFdbk2',
    'abrupt4xCO2',
    'amip4xCO2',
    'amipFuture',
    'amip4K',
    'aqua4xCO2',
    'aquaControl',
    'aqua4K',
    'esmHistorical',
    'esmControl',
    'historicalGHG',
    'historicalNat',
    'historicalExt',
    'rcp26',
    'rcp45',
    'rcp60',
    'rcp85',
    'Other'
]

replaced_realms = {
    'CMIP5': {},
    'CMIP6': {
        'aerosol': 'aerosol - Aerosol',
        'atmos': 'atmos - Atmosphere',
        'atmosChem': 'atmosChem - Atmospheric Chemistry',
        'land': 'land - Land Surface',
        'landIce': 'landIce - Land Ice',
        'ocean': 'ocean - Ocean',
        'ocnBgchem': 'ocnBgchem - Ocean Biogeochemistry',
        'seaIce': 'seaIce - Sea Ice'
    }
}

removed_realms = [
        'aerosol',
        'atmos',
        'atmosChem',
        'land',
        'landIce',
        'ocean',
        'ocnBgchem',
        'seaIce'
]

replaced_variables = {
    'CMIP5': {
        'air pressure': 'phalf - Pressure on Model Half-Levels',
        'air pressure at cloud top': 'pctisccp - ISCCP Mean Cloud Top Pressure',
        'air pressure at convective cloud base': 'ccb - Air Pressure at Convective Cloud Base',
        'air pressure at convective cloud top': 'cct - Air Pressure at Convective Cloud Top',
        'air pressure at sea level': 'psl - Sea Level Pressure',
        'air temperature': 'ta - Air Temperature',
        'area fraction': 'c4PftFrac - Percentage Cover by C4 Plant Functional Type',
        'atmosphere cloud condensed water content': 'clwvi - Condensed Water Path',
        'atmosphere cloud ice content': 'clivi - Ice Water Path',
        'atmosphere heat diffusivity': 'edt - Eddy Diffusivity Coefficient for Temperature',
        'atmosphere momentum diffusivity': 'evu - Eddy Viscosity Coefficient for Momentum',
        'atmosphere water vapor content': 'prw - Water Vapor Path',
        'cloud area fraction': 'clt - Total Cloud Cover Percentage',
        'cloud area fraction in atmosphere layer': 'cl - Percentage Cloud Cover',
        'convective cloud area fraction': 'cltc - Convective Cloud Cover Percentage',
        'convective cloud area fraction in atmosphere layer': 'clc - Convective Cloud Area Percentage',
        'convective precipitation flux': 'prc - Convective Precipitation',
        'convective rainfall flux': 'prcprof - Convective Rainfall Flux',
        'convective snowfall flux': 'prsnc - Convective Snowfall Flux',
        'downward sea ice basal salt flux': 'sfdsi - Downward Sea Ice Basal Salt Flux',
        'downwelling longwave flux in air': 'rld - Downwelling Longwave Radiation',
        'downwelling shortwave flux in air': 'rsd - Downwelling Shortwave Radiation',
        'eastward wind': 'ua - Eastward Wind',
        'geopotential height': 'zg - Geopotential Height',
        'global average sea level change': 'zos - Sea Surface Height Above Geoid',
        'global average thermosteric sea level change': 'zostoga - Global Average Thermosteric Sea Level Change',
        'gross primary productivity of carbon': 'gpp - Carbon Mass Flux out of Atmosphere Due to Gross Primary Production on Land [kgC m-2 s-1]',
        'heat flux correction': 'hfcorr - Heat Flux Correction',
        'heterotrophic respiration carbon flux': 'rh - Total Heterotrophic Respiration on Land as Carbon Mass Flux [kgC m-2 s-1]',
        'isccp cloud area fraction': 'clisccp - ISCCP Cloud Area Percentage',
        'lagrangian tendency of air pressure': 'wap - Omega (=dp/dt)',
        'land area fraction': 'sftlf - Percentage of the Grid Cell Occupied by Land (Including Lakes)',
        'land ice area fraction': 'sftgif - Land Ice Area Percentage',
        'large scale rainfall flux': 'prlsprof - Stratiform Rainfall Flux',
        'large scale snowfall flux': 'prlsns - Stratiform Snowfall Flux',
        'leaf area index': 'lai - Leaf Area Index',
        'liquid water content of snow layer': 'lwsnl - Liquid Water Content of Snow Layer',
        'litter carbon content': 'cLitter - Carbon Mass in Litter Pool',
        'litter carbon flux': 'fVegLitter - Total Carbon Mass Flux from Vegetation to Litter',
        'mass fraction of cloud ice in air': 'cli - Mass Fraction of Cloud Ice',
        'mass fraction of cloud liquid water in air': 'clw - Mass Fraction of Cloud Liquid Water',
        'mass fraction of convective cloud ice in air': 'clic - Mass Fraction of Convective Cloud Ice',
        'mass fraction of convective cloud liquid water in air': 'clwc - Mass Fraction of Convective Cloud Liquid Water',
        'mass fraction of stratiform cloud ice in air': 'clis - Mass Fraction of Stratiform Cloud Ice',
        'mass fraction of stratiform cloud liquid water in air': 'clws - Mass Fraction of Stratiform Cloud Liquid Water',
        'mass fraction of water in air': 'h2o - Mass Fraction of Water',
        'moisture content of soil layer': 'mrsos - Moisture in Upper Portion of Soil Column',
        'mole fraction of ozone in air': 'toz - Total Column Ozone',
        'net downward radiative flux at top of atmosphere model': 'rtmt - Net Downward Radiative Flux at Top of Model',
        'net primary productivity of carbon': 'npp - Net Primary Production on Land as Carbon Mass Flux [kgC m-2 s-1]',
        'northward ocean heat transport': 'hfbasin - Northward Ocean Heat Transport',
        'northward ocean heat transport due to bolus advection': 'hfbasin - Northward Ocean Heat Transport',
        'northward ocean heat transport due to diffusion': 'hfbasinpmdiff - Northward Ocean Heat Transport Due to Parameterized Mesoscale Diffusion',
        'northward ocean heat transport due to gyre': 'htovgyre - Northward Ocean Heat Transport Due to Gyre',
        'northward ocean heat transport due to overturning': 'htovovrt - Northward Ocean Heat Transport Due to Overturning',
        'northward wind': 'va - Northward Wind',
        'ocean mixed layer thickness defined by mixing scheme': 'omldamax - Mean Daily Maximum Ocean Mixed Layer Thickness Defined by Mixing Scheme',
        'ocean mixed layer thickness defined by sigma t': 'mlotst - Ocean Mixed Layer Thickness Defined by Sigma T',
        'ocean volume': 'volcello - Ocean Grid-Cell Volume',
        'plant respiration carbon flux': 'ra - Carbon Mass Flux into Atmosphere Due to Autotrophic (Plant) Respiration on Land [kgC m-2 s-1]',
        'precipitation flux': 'pr - Precipitation',
        'rainfall flux': 'pr - Precipitation',
        'relative humidity': 'hur - Relative Humidity',
        'root depth': 'rootd - Maximum Root Depth',
        'runoff flux': 'mrro - Total Runoff',
        'sea area fraction': 'sftof - Sea Area Percentage',
        'sea floor depth below geoid': 'deptho - Sea Floor Depth Below Geoid',
        'sea ice area fraction': 'siconc - Sea-Ice Area Percentage (Ocean Grid)',
        'sea ice thickness': 'sithick - Sea Ice Thickness',
        'sea ice transport across line': 'sidmasstranx - X-Component of Sea-Ice Mass Transport',
        'sea ice x velocity': 'siu - X-Component of Sea-Ice Velocity',
        'sea ice y velocity': 'siv - Y-Component of Sea-Ice Velocity',
        'sea surface height above geoid': 'zos - Sea Surface Height Above Geoid',
        'sea surface salinity': 'sos - Sea Surface Salinity',
        'sea surface temperature': 'tos - Sea Surface Temperature',
        'sea water potential density': 'opottempmint - Integral with Respect to Depth of Product of Sea Water Density and Potential Temperature',
        'sea water potential temperature': 'thetaoga - Global Average Sea Water Potential Temperature',
        'sea water salinity': 'soga - Global Mean Sea Water Salinity',
        'sea water x velocity': 'uo - Sea Water X Velocity',
        'sea water y velocity': 'vo - Sea Water Y Velocity',
        'snowfall flux': 'prsn - Snowfall Flux',
        'soil carbon content': 'cSoil - Carbon Mass in Model Soil Pool',
        'soil frozen water content': 'mrfso - Soil Frozen Water Content',
        'soil moisture content': 'mrso - Total Soil Moisture Content',
        'soil moisture content at field capacity': 'mrsofc - Capacity of Soil to Store Water (Field Capacity)',
        'soil temperature': 'tsl - Temperature of Soil',
        'specific humidity': 'hus - Specific Humidity',
        'stratiform cloud area fraction in atmosphere layer': 'cls - Percentage Cover of Stratiform Cloud',
        'surface air pressure': 'ps - Surface Air Pressure',
        'surface altitude': 'orog - Surface Altitude',
        'surface downward eastward stress': 'tauu - Surface Downward Eastward Wind Stress',
        'surface downward heat flux in sea water': 'hfds - Downward Heat Flux at Sea Water Surface',
        'surface downward latent heat flux': 'hfls - Surface Upward Latent Heat Flux',
        'surface downward northward stress': 'tauv - Surface Downward Northward Wind Stress',
        'surface downward sensible heat flux': 'hfss - Surface Upward Sensible Heat Flux',
        'surface downward x stress': 'tauuo - Sea Water Surface Downward X Stress',
        'surface downward y stress': 'tauvo - Sea Water Surface Downward Y Stress',
        'surface downwelling longwave flux in air': 'rlds - Surface Downwelling Longwave Radiation',
        'surface downwelling longwave flux in air assuming clear sky': 'rldscs - Surface Downwelling Clear-Sky Longwave Radiation',
        'surface downwelling shortwave flux in air': 'rsds - Surface Downwelling Shortwave Radiation',
        'surface downwelling shortwave flux in air assuming clear sky': 'rsdscs - Surface Downwelling Clear-Sky Shortwave Radiation',
        'surface net downward longwave flux': 'rlds - Surface Downwelling Longwave Radiation',
        'surface partial pressure of carbon dioxide in sea water': 'spco2 - Surface Aqueous Partial Pressure of CO2',
        'surface runoff flux': 'mrros - Surface Runoff',
        'surface snow amount': 'snw - Surface Snow Amount',
        'surface snow area fraction': 'snc - Snow Area Percentage',
        'surface snow melt flux': 'snm - Surface Snow Melt',
        'surface snow thickness': 'snd - Snow Depth',
        'surface temperature': 'tslsi - Surface Temperature Where Land or Sea Ice',
        'surface upward latent heat flux': 'hfls - Surface Upward Latent Heat Flux',
        'surface upward sensible heat flux': 'hfss - Surface Upward Sensible Heat Flux',
        'surface upwelling longwave flux in air': 'rlus - Surface Upwelling Longwave Radiation',
        'surface upwelling shortwave flux in air': 'rsus - Surface Upwelling Shortwave Radiation',
        'surface upwelling shortwave flux in air assuming clear sky': 'rsuscs - Surface Upwelling Clear-Sky Shortwave Radiation',
        'tendency of air temperature': 'tnt - Tendency of Air Temperature',
        'tendency of air temperature due to advection': 'tnta - Tendency of Air Temperature Due to Advection',
        'tendency of air temperature due to radiative heating': 'tntr - Tendency of Air Temperature Due to Radiative Heating',
        'tendency of specific humidity': 'tnhus - Tendency of Specific Humidity',
        'tendency of specific humidity due to advection': 'tnhusa - Tendency of Specific Humidity Due to Advection',
        'tendency of specific humidity due to convection': 'tnhusc - Tendency of Specific Humidity Due to Convection',
        'tendency of specific humidity due to diffusion': 'tnhusd - Tendency of Specific Humidity Due to Numerical Diffusion',
        'tendency of specific humidity due to model physics': 'tnhusmp - Tendency of Specific Humidity Due to Model Physics',
        'toa incoming shortwave flux': 'rsdt - TOA Incident Shortwave Radiation',
        'toa outgoing longwave flux': 'rlut - TOA Outgoing Longwave Radiation',
        'toa outgoing longwave flux assuming clear sky': 'rlutcs - TOA Outgoing Clear-Sky Longwave Radiation',
        'toa outgoing shortwave flux': 'rsut - TOA Outgoing Shortwave Radiation',
        'toa outgoing shortwave flux assuming clear sky': 'rsutcs - TOA Outgoing Clear-Sky Shortwave Radiation',
        'transpiration flux': 'tran - Transpiration',
        'upwelling longwave flux in air': 'rlu - Upwelling Longwave Radiation',
        'upwelling shortwave flux in air': 'rsu - Upwelling Shortwave Radiation',
        'vegetation carbon content': 'cVeg - Carbon Mass in Vegetation',
        'water evaporation flux': 'evs - Water Evaporation Flux Where Ice Free Ocean over Sea',
        'water evaporation flux from canopy': 'evspsblveg - Evaporation from Canopy',
        'water evaporation flux from soil': 'evspsblsoi - Water Evaporation from Soil',
        'water flux correction': 'wfcorr - Water Flux Correction',
        'wind speed': 'sfcWindmax - Daily Maximum Near-Surface Wind Speed',
        'atmosphere convective mass flux': 'mc - Convective Mass Flux',
        'eastward sea ice velocity': 'siu - X-Component of Sea-Ice Velocity',
        'northward sea ice velocity': 'siv - Y-Component of Sea-Ice Velocity',
        'ocean chlorophyll': 'chl - Mass Concentration of Total Phytoplankton Expressed as Chlorophyll in Sea Water',
        'snow temperature': 'sitemptop - Surface Temperature of Sea Ice',
        'surface albedo': 'albdiffbnd - Diffuse Surface Albedo for Each Band',
        'water sublimation flux': 'sbl - Surface Snow and Ice Sublimation Flux'
    },
    'CMIP6': {
        'prra - Rainfall Flux where Ice Free Ocean over Sea': 'prra - Rainfall Flux'
    }
}

removed_variables = [
        'prra - Rainfall Flux where Ice Free Ocean over Sea'
]