variable_data = [
    {'project_name': 'CMIP5',
     'variables': [
         'air pressure',
         'air pressure at cloud top',
         'air pressure at convective cloud base',
         'air pressure at convective cloud top',
         'air pressure at sea level',
         'air temperature',
         'area fraction',
         'atmosphere cloud condensed water content',
         'atmosphere cloud ice content',
         'atmosphere convective mass flux',
         'atmosphere heat diffusivity',
         'atmosphere momentum diffusivity',
         'atmosphere water vapor content',
         'cloud area fraction',
         'cloud area fraction in atmosphere layer',
         'convective cloud area fraction',
         'convective cloud area fraction in atmosphere layer',
         'convective precipitation flux',
         'convective rainfall flux',
         'convective snowfall flux',
         'downward sea ice basal salt flux',
         'downwelling longwave flux in air',
         'downwelling shortwave flux in air',
         'eastward sea ice velocity',
         'eastward wind',
         'geopotential height',
         'global average sea level change',
         'global average thermosteric sea level change',
         'gross primary productivity of carbon',
         'heat flux correction',
         'heterotrophic respiration carbon flux',
         'isccp cloud area fraction',
         'lagrangian tendency of air pressure',
         'land area fraction',
         'land ice area fraction',
         'large scale rainfall flux',
         'large scale snowfall flux',
         'leaf area index',
         'liquid water content of snow layer',
         'litter carbon content',
         'litter carbon flux',
         'mass fraction of cloud ice in air',
         'mass fraction of cloud liquid water in air',
         'mass fraction of convective cloud ice in air',
         'mass fraction of convective cloud liquid water in air',
         'mass fraction of stratiform cloud ice in air',
         'mass fraction of stratiform cloud liquid water in air',
         'mass fraction of water in air',
         'moisture content of soil layer',
         'mole fraction of ozone in air',
         'net downward radiative flux at top of atmosphere model',
         'net primary productivity of carbon',
         'northward ocean heat transport',
         'northward ocean heat transport due to bolus advection',
         'northward ocean heat transport due to diffusion',
         'northward ocean heat transport due to gyre',
         'northward ocean heat transport due to overturning',
         'northward sea ice velocity',
         'northward wind',
         'ocean chlorophyll',
         'ocean mixed layer thickness defined by mixing scheme',
         'ocean mixed layer thickness defined by sigma t',
         'ocean volume',
         'plant respiration carbon flux',
         'precipitation flux',
         'rainfall flux',
         'relative humidity',
         'root depth',
         'runoff flux',
         'sea area fraction',
         'sea floor depth below geoid',
         'sea ice area fraction',
         'sea ice thickness',
         'sea ice transport across line',
         'sea ice x velocity',
         'sea ice y velocity',
         'sea surface height above geoid',
         'sea surface salinity',
         'sea surface temperature',
         'sea water potential density',
         'sea water potential temperature',
         'sea water salinity',
         'sea water x velocity',
         'sea water y velocity',
         'snow temperature',
         'snowfall flux',
         'soil carbon content',
         'soil frozen water content',
         'soil moisture content',
         'soil moisture content at field capacity',
         'soil temperature',
         'specific humidity',
         'stratiform cloud area fraction in atmosphere layer',
         'surface air pressure',
         'surface albedo',
         'surface altitude',
         'surface downward eastward stress',
         'surface downward heat flux in sea water',
         'surface downward latent heat flux',
         'surface downward northward stress',
         'surface downward sensible heat flux',
         'surface downward x stress',
         'surface downward y stress',
         'surface downwelling longwave flux in air',
         'surface downwelling longwave flux in air assuming clear sky',
         'surface downwelling shortwave flux in air',
         'surface downwelling shortwave flux in air assuming clear sky',
         'surface net downward longwave flux',
         'surface partial pressure of carbon dioxide in sea water',
         'surface runoff flux',
         'surface snow amount',
         'surface snow area fraction',
         'surface snow melt flux',
         'surface snow thickness',
         'surface temperature',
         'surface upward latent heat flux',
         'surface upward sensible heat flux',
         'surface upwelling longwave flux in air',
         'surface upwelling shortwave flux in air',
         'surface upwelling shortwave flux in air assuming clear sky',
         'tendency of air temperature',
         'tendency of air temperature due to advection',
         'tendency of air temperature due to radiative heating',
         'tendency of specific humidity',
         'tendency of specific humidity due to advection',
         'tendency of specific humidity due to convection',
         'tendency of specific humidity due to diffusion',
         'tendency of specific humidity due to model physics',
         'time',
         'toa incoming shortwave flux',
         'toa outgoing longwave flux',
         'toa outgoing longwave flux assuming clear sky',
         'toa outgoing shortwave flux',
         'toa outgoing shortwave flux assuming clear sky',
         'transpiration flux',
         'upwelling longwave flux in air',
         'upwelling shortwave flux in air',
         'vegetation carbon content',
         'water evaporation flux',
         'water evaporation flux from canopy',
         'water evaporation flux from soil',
         'water flux correction',
         'water sublimation flux',
         'wind speed',
         'Other'
     ]},
    {'project_name': 'CMIP6',
     'variables': [

     ]},
    {'project_name': 'AIMS',
     'variables': [

     ]},
]
